# Generated by Django 5.0.3 on 2024-04-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_delivrable_options_alter_etape_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='delivrable',
            table='delivrable',
        ),
        migrations.AlterModelTable(
            name='etape',
            table='etape',
        ),
    ]
