# Generated by Django 5.0.4 on 2024-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_delete_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionSujet',
            fields=[
                ('idselection', models.AutoField(db_column='idselection', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'selectionsujet',
                'managed': False,
            },
        ),
    ]
