# Generated by Django 5.0.3 on 2024-04-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivrable',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='etape',
            options={'managed': False},
        ),
    ]
