# Generated by Django 5.0.3 on 2024-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_delivrable_etape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivrable',
            name='idDelivrable',
            field=models.AutoField(db_column='idDelivrable', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etape',
            name='idEtape',
            field=models.AutoField(db_column='idEtape', primary_key=True, serialize=False),
        ),
    ]
