# Generated by Django 5.0.3 on 2024-03-30 16:03

import django.db.models.deletion
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_delivrable_iddelivrable_alter_etape_idetape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivrable',
            name='idDelivrable',
            field=models.AutoField(db_column='iddelivrable', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delivrable',
            name='typeFichier',
            field=models.TextField(db_column='typefichier', validators=[polls.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='etape',
            name='idDelivrable',
            field=models.ForeignKey(db_column='iddelivrable', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.delivrable'),
        ),
        migrations.AlterField(
            model_name='etape',
            name='idEtape',
            field=models.AutoField(db_column='idetape', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etape',
            name='idPeriode',
            field=models.ForeignKey(db_column='idperiode', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.periode'),
        ),
    ]
