# Generated by Django 5.0.3 on 2024-04-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_fichierdelivrable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superviseur',
            fields=[
                ('idsuperviseur', models.AutoField(db_column='idsuperviseur', primary_key=True, serialize=False)),
                ('specialite', models.TextField(db_column='specialite')),
            ],
            options={
                'db_table': 'superviseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('idsupervision', models.AutoField(db_column='idsupervision', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='description')),
            ],
            options={
                'db_table': 'supervision',
                'managed': False,
            },
        ),
    ]
