# Generated by Django 5.0.3 on 2024-04-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_selectionsujet'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeUe',
            fields=[
                ('idetapeue', models.AutoField(db_column='idetapeue', primary_key=True, serialize=False)),
                ('etapecourante', models.BooleanField(db_column='etapecourante', default=False)),
            ],
            options={
                'db_table': 'etapeue',
                'managed': False,
            },
        ),
    ]
